### ISSUE TITLE
Chrome Browser crash while video upload on server  

### ISSUE THREAD

**Issue by manjinderiolcp** [muaz-khan/RecordRTC#198] opened 2016-11-28 04:43 UTC
Hi,

I am using WebRTC video recording and upload video on server with MVC .net(Demo) 
Video uploading on server repeat after some interval(50000) of time. Every time video size contain approx(3.5mb). Its working fine for first 4-5 time. but after that Chrome crash and show message given below.

**Google Chrome ran out of memory while trying to display this webpage**

I think its because of video cache/buffer. chrome memory full with cache/buffer.  Please suggest me how to clear cache/buffer or any other solution to resolve this problem.

Thanks in Advance

**Comment by vrajroham** [comment] 2016-12-19 09:50
Hey @manjinderiolcp, 
Issue specifically occurs in chrome only? Did you tested from another machine?

**Comment by muaz-khan** [comment] 2017-03-03 11:59
**Unable to reproduce this bug.** Closing for now.

**Closed by muaz-khan** 2017-03-03 11:59 UTC

**Comment by qyj19920704** [comment] 2020-06-02 02:13
> Hi,
> 
> I am using WebRTC video recording and upload video on server with MVC .net(Demo)
> Video uploading on server repeat after some interval(50000) of time. Every time video size contain approx(3.5mb). Its working fine for first 4-5 time. but after that Chrome crash and show message given below.
> 
> **Google Chrome ran out of memory while trying to display this webpage**
> 
> I think its because of video cache/buffer. chrome memory full with cache/buffer. Please suggest me how to clear cache/buffer or any other solution to resolve this problem.
> 
> Thanks in Advance

Has this oom problem been solved?
