### ISSUE TITLE
Firefox Crash

### ISSUE THREAD

**Issue by israelsousa21** [muaz-khan/RecordRTC#192] opened 2016-11-11 18:48 UTC
Hello, I got a crash when I try to click the button to upload video to de server on Record-RTC-Upload-PHP. That happend after I update the firefox, I dont rememberd the last version was I use, the current veersion is 49.0.2. Some one got this problem?

**Comment by vrajroham** [comment] 2016-11-13 19:06
Duplicate of #192

**Closed** 2016-11-13 19:57 UTC
