### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by 583** [muaz-khan/RecordRTC#203] opened 2016-12-19 05:05 UTC
I record video 10 minutes and Stop recording. 

The JavaScript Maximum call stack size exceeded

How to solve?

**Comment by vrajroham** [comment] 2017-01-06 08:39
hey @583 which browser you are using? what is it's version?

**Comment by vrajroham** [comment] 2017-01-06 08:41
Take a look at issue #1 . May it help you.

**Comment by JimMcLeod** [comment] 2017-01-12 11:31
I'm getting the same issue.
Browser: Chrome Version 55.0.2883.87 (64-bit)
OS: Linux Mint
also getting the issue on Windows 7 and 10

**Comment by JimMcLeod** [comment] 2017-01-19 15:04
Any ideas whats happening here? 

Seems to be related to the quality of the camera. My 640x480 webcam can record 10 minutes without the error but on my Galaxy Note (1080p) I get nowhere near that.

**Comment by vrajroham** [comment] 2017-01-31 12:54
@JimMcLeod

I think your code is recursively executing without breaking it.
This error occurs generally  because of recurssion. I'll suggest debug your code. Can't predict from this snippet what's wrong with it. If possible create [fiddle](https://jsfiddle.net/) and share the link.

**Comment by JimMcLeod** [comment] 2017-02-01 09:56
That snippet is from your code. I was just pointing out where the error occurs.

As I mentioned in my previous post it is related to the size (in memory) of the video. Higher quality videos cause the error with less record time - i.e. a 1080p video might reliably save 1 minute of video but a 640x480 webcan might get 10 minutes.

**Comment by tero** [comment] 2017-02-15 09:04
I can confirm this is issue on RecordRTC and it show up only with Chrome. Might be related to WhammyRecorder because with Firefox it works.

**Comment by JimMcLeod** [comment] 2017-02-15 09:21
Yes, I am using WhammyRecorder.

**Comment by JimMcLeod** [comment] 2017-02-23 08:28
Got a quick and dirty fix for this issue.

In the file RecordRTC.js replace the function asyncLoop(o) with this:

    function asyncLoop(o) {
        var i = -1,
            length = o.length;

        var loop = function() {
            i++;
            if (i === length) {
                o.callback();
                return;
            }
            setTimeout(function () {
                o.functionToLoop(loop, i);
            }, 1)
        };
            loop(); //init
    }

I've recorded a 20 minute, 201mb video with this small hack. Processing takes a bit longer but at least it works.

**Comment by muaz-khan** [comment] 2017-03-01 11:27
[Merged](https://github.com/muaz-khan/RecordRTC/commit/7ad5f02a3c360d8f315ab0cf5e4700cc37f60e5b). Thanks @JimMcLeod .

**Closed by muaz-khan** 2017-03-01 11:27 UTC
