### ISSUE TITLE
audio will lost in beginning of the video and end of video

### ISSUE THREAD

**Issue by edushare** [muaz-khan/RecordRTC#171] opened 2016-09-05 10:25 UTC
try to record a video,  then get notice that, audio is lost in beginning and end of the video for few second while video is still ok.

**Comment by adityaupadyayula** [comment] 2016-09-09 04:50
hai Muaz same issue for me audio is fine few seconds while recording. later on no voice is getting recording.please help us to fix the issue asap ur help is appreciated..

**Comment by adityaupadyayula** [comment] 2016-09-09 04:51
Also recording is not getting started in windows 10 64bit version need your quick help

**Comment by thijstriemstra** [comment] 2016-09-28 23:08
what version of recordrtc, what browser and what operating system are you using?

**Comment by muaz-khan** [comment] 2017-03-03 12:35
Closing for now. Unable to reproduce on Win10 & Mac.

**Closed by muaz-khan** 2017-03-03 12:35 UTC
