### ISSUE TITLE
Freezes in Chrome

### ISSUE THREAD

**Issue by redwerk** [muaz-khan/RecordRTC#269] opened 2017-05-30 10:22 UTC
We have found inexplicable freezes of video recording in Chrome. We opened an issue for the library video.js (https://github.com/collab-project/videojs-record/issues/146), because we record video with it and RecordRTC. We think it can be related to RecordRTC library, because there are really similar old issues pointed out (https://github.com/collab-project/videojs-record/issues/54 or  https://github.com/collab-project/videojs-record/issues/114). We have revised our code, and no bugs are reported with any of our tracking tools, in console and no external developers could spot any issues.

Here is the problem description:
Sometimes when starting a recording, the plugin shows just a static image instead of video recording. The video doesn't exist after the recording is stopped. We’ve set debug to true in order to figure out additional information, but we haven’t seen any errors in browser console. Library debug log write that video is recording.

The bug could be reproduced randomly. It doesn’t depend on hardware, as it could be reproduced on devices with 30% of cpu usage and 40-50% of memory usage and on high loaded devices. It could be reproduced with built-in webcams as well as usb webcams.
It was reproduced on Windows and Mac OS. 

We tried to debug our scripts to detect the issue, but the only thing we found, is that after the start it records for 1 second and stops with static image and without errors. After calling stop recording video doesn't exist.

After this freeze Chrome tab doesn't respond and sometimes it can't be closed. If Chrome tab is closed after that and a new one is opened, recording is impossible: the camera is not found and recorder is not created. Only the browser restart helps in this situation.

There are no errors in browser console at that moment. Actually, that's why we think that it can be related to issues with memory leaks.

We have also noticed another issue:
When new usb cam is connected and driver is still installing, plug-in loges in browser console that camera is found and available, but only black screen and loading image are shown. Maybe, both of issues have the same root.

**Browsers and versions affected**
Browsers: it was reproduced on Windows and Mac OS. In 57.0.2987.133 and 58.0.3029.81 Chrome Versions:
videojs 5.18.4
videojs-record v1.6.1
RecordRTC v5.4.1

**Comment by muaz-khan** [comment] 2017-06-04 05:59
Please try RecordRTC `v5.4.1` from `npm install recorder@5.4.1` or otherwise https://github.com/muaz-khan/RecordRTC/releases/tag/5.4.1

i.e. **do not use CDN**. 

Reason: CDN always uses most recent updates from github. That's why it can bring unexpected issues.

*PS. I didn't able to reproduce this bug myself yet, though.*

**Comment by muaz-khan** [comment] 2017-06-04 06:15
**Try following during recording:**

```javascript
DiskStorage.dbName = 'my_own_db';
DiskStorage.dataStoreName = 'recordRTC_logs';
DiskStorage.init();

DiskStorage.Store({
    audioBlob: 'page load'
});

console.log = console.error = console.debug = console.warn = window.onerror = function() {
    var newLog = JSON.stringify(arguments);

    DiskStorage.Fetch(function(previousLogs, type) {
        if(type !== 'audioBlob') return;

        DiskStorage.callback  = function() {};

        previousLogs += '\n' + newLog;
        DiskStorage.Store({
            audioBlob: previousLogs
        });
    });
};
```

**Try following after crash (reload the page):**

```javascript
DiskStorage.dbName = 'my_own_db';
DiskStorage.dataStoreName = 'recordRTC_logs';
DiskStorage.init();

DiskStorage.Fetch(function(previousLogs, type) {
    if(type !== 'audioBlob') return;

    DiskStorage.callback  = function() {};

    // alert or console-log to view the logs
    alert(previousLogs);
});
```

**Comment by thijstriemstra** [comment] 2017-06-12 16:39
> i.e. do not use CDN.

I see. I will update links in my projects to use a local recordrtc version. Perhaps you should put a note in the readme that the CDN is basically not good for anything?

**Comment by muaz-khan** [comment] 2017-06-12 17:03
Personally I prefer CDN, because
1. It is always up-to-dated (usually I update once per weekly [according to issues/bugs])
2. All recent bugs/issues are fixed in this (CDN) build
3. It is well tested as well, before publishing to CDN (I take this point seriously!)

i.e. whenever someone reports a bug, I fix it (ASAP), test all possible implications (demos & browsers), and update the CDN.

Big projects (or production websites) are recommended to use [specific github releases](https://github.com/muaz-khan/RecordRTC/releases), though.

**Comment by thijstriemstra** [comment] 2017-06-12 17:05
Ok it kinda contradicts your previous comment but I understand your point.

**Comment by maxpaj** [comment] 2017-06-14 08:46
Sorry, from where is the DiskStorage API available?

**Comment by muaz-khan** [comment] 2017-06-14 17:45
Please try all mime-types:

```javascript
options.mimeType = 'video/webm\;codecs=vp8'; // vp8
options.mimeType = 'video/webm\;codecs=vp9'; // vp9
options.mimeType = 'video/webm\;codecs=h264'; // h264
options.mimeType = 'video/x-matroska;codecs=avc1'; // mkv
```

Remove audio tracks or reconstruct the stream:

```javascript
var newStream = new MediaStream();

// audio+video (all tracks)
originalStream.getAudioTracks().concat(originalStream.getVideoTracks()).forEach(function(track) {
    newStream.addTrack(track);
});

// or merely video tracks( ignore audio tracks )
newStream = new MediaStream();
originalStream.getVideoTracks().forEach(function(track) {
    newStream.addTrack(track);
});

recorder = new RecordRTC(originalStream, options);
```

It is recommended to force (if possible) camera-resolutions via getUserMedia API; to get most accurate or a better stream object:

```javascript
hints = {
    width: {
        min: 640,
        max: 640
    },
    height: {
        min: 360,
        max: 360
    },
    frameRate: {
        min: 30,
        max: 30
    },
    aspectRatio: 1.77
};
navigator.mediaDevices.getUserMedia(hints).then(success).catch(failure);
```

PS. Prefer `RecordRTC` object over MRecordRTC.

**Comment by maxpaj** [comment] 2017-06-15 08:39
Thanks for the reply Muaz. I haven't tried your suggestions yet, but a thought that occurred:

When using RecordRTC, the video data is stored as blobs in the browser cache? If the issue here is that the data can't be written to the cache, would it make sense to change it so that the data is streamed directly from the video source to a remote location (never touching the browser or computer storage)?

**Comment by redwerk** [comment] 2017-06-15 13:01
We took your code for getting errors on video freeze. It took some time, because this bug is reproduced randomly. Here you can find all the logs we’ve managed to get:
1.https://www.dropbox.com/s/0b6zz2ba0rl739d/bc3039378d.jpg?dl=0 (FF on Mac)
2.https://www.dropbox.com/s/syvugd70f3v604q/error.PNG?dl=0 (Chrome on Windows 10)
3.https://www.dropbox.com/s/ps7mton52vboerk/Screen%20Shot%202017-06-15%20at%2013.10.34.png?dl=0 (Chrome om Mac)
Also, we see this error in our logs even if no freeze: "URL.createObjectURL(stream) has been deprecated". You use this in your library and once video was freezed and only this error was in logs. So, maybe, you need to take a look on this error. We found some relevant articles, like: https://www.fxsitecompat.com/en-CA/docs/2017/url-createobjecturl-stream-has-been-deprecated/
Thank you for your help!

**Comment by redwerk** [comment] 2017-07-05 11:28
Thank you for all responses!
We found that such error occur mostly on the 57 and 58 Chrome version. And we fixed it through changing videoMimeType to 'video/webm;codecs=vp9'.
Thank you for your help!

**Closed** 2017-07-05 11:28 UTC
