### ISSUE TITLE
Recorded video need in .mp4 format

### ISSUE THREAD

**Issue by deepak-arora** [muaz-khan/RecordRTC#178] opened 2016-09-21 06:21 UTC
Hi,

Is it possible to get the recorded video in to .mp4 format instead of .webm, because .webm video is not playing in iphone/ios.

Thanks

**Comment by thijstriemstra** [comment] 2016-09-28 19:25
Apparently it's possible [according to this example](https://github.com/muaz-khan/RecordRTC#record-audiovideo-in-firefox), but only in Firefox (not sure if it's available on IOS). Read the docs!

**Comment by thijstriemstra** [comment] 2016-09-28 22:29
Duplicate of #97.

**Comment by muaz-khan** [comment] 2017-03-03 12:20
`index.html` supports h264.

**Closed by muaz-khan** 2017-03-03 12:20 UTC
